# Overgrown City

ASide:
  - Room: "1a start"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "1b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      
  - Room: "1c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru"
      Update:
        X: 704
        Width: 48
      
  - Room: "1d"
    Holes:
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 488
      Y: 528
      Update:
        Default: true
      
  - Room: "1e"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 1
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 120
      Update:
        Default: true
      
  - Room: "Strawberry"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal