# Grandmaster Heart Side

ASide:
  - Room: "room_1"
    Core:
      All: hot
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 83
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: two
        Difficulty: perfect
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
        
  - Room: "room_2"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
      LowBound: 53
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: perfect
    Tweaks:
    - Name: "spawn"
      X: 64
      Y: 608
      Update:
        Default: true
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
        
  - Room: "room_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: perfect
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
       
  - Room: "room_4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - CustomWarp: true
      ReqOut:
        Dashes: two
        Difficulty: perfect
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true