# The Correlation

ASide:
  - Room: "01"
    Core:
      All: Hot
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "02"
    Core:
      All: Hot
      Right: Cold
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
        Dashes: two
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "exit"
        ReqBoth:
          Dashes: two
          Difficulty: normal
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 328
        Y: 136
        
  - Room: "03"
    Core:
      All: Cold
      Right: Hot
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
        Difficulty: normal
        
  - Room: "04"
    Core:
      All: Hot
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
 
  - Room: "05"
    Core:
      All: Cold
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: two
        Difficulty: hard
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 48
        Y: 64
      
  - Room: "06"
    Core:
      All: Hot
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      ID: 434
      Update:
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 253
        Y: 20
      
  - Room: "07"
    Core:
      All: Hot
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "secret"
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Dashes: zero
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: hard
    Subrooms:
    - Room: "secret"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 256
      Y: 224
      Update:
        X: 248
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Add: true
        X: 432
        Y: 0
        Width: 16
        Height: 224
    - Name: "spawn"
      Update:
        Add: true
        X: 440
        Y: 208
    - Name: "jumpThru"
      ID: 425
      Update:
        Width: 16
    - Name: "fgTiles"
      X: 33
      Y: 27
      Update:
        Tile: "k" # Core
    - Name: "fgTiles"
      X: 34
      Y: 27
      Update:
        Tile: "k" # Core
      
  - Room: "08"
    Core:
      All: Hot
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard